sudo: required
services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker-skel"
  env: ReactDockerSkel-env
  bucket_name: "elasticbeanstalk-ap-south-1-237392829617"
  bucket_path: "ReactDockerSkel"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"