sudo: required
services:
  - docker

before_install:
  - docker build -t sandjaie/react-docker-skel -f Dockerfile.dev .

script:
  - docker run -e CI=true sandjaie/react-docker-skel npm run test -- --coverage