sudo: required
services:
  - docker

before_install:
  - docker build -t sandjaie/react-docker-skel -f Dockerfile.dev .

script:
  - docker run -e CI=true sandjaie/react-docker-skel npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker-skel"
  env: ReactDockerSkel-env
  bucket_name: "elasticbeanstalk-ap-south-1-237392829617"
  bucket_path: "ReactDockerSkel"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  